Controllers/Cuenta_BancariaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using pc2_leonardo.Data;
using pc2_leonardo.Models;
using Microsoft.EntityFrameworkCore;
using System.Dynamic;


namespace pc2_leonardo.Controllers
{
    public class Cuenta_BancariaController : Controller
    {
        private readonly ILogger<Cuenta_BancariaController> _logger;
        private readonly ApplicationDbContext _context;

        public Cuenta_BancariaController(ILogger<Cuenta_BancariaController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nombre_Titular,Tipo_Cuenta,SaldoInicial,Email")] CuentaBancarias cuenta)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cuenta);
                await _context.SaveChangesAsync();
                
                TempData["Message"] = "Cuenta creada con éxito."; // Usa TempData para almacenar el mensaje

                return RedirectToAction("Index");
            }

            return View("Index");
        }
        
        public IActionResult ListarCuentas()
        {
            var cuentas = _context.DataCuentaBancarias.ToList();
            return View("ListarCuentas", cuentas); // Asegúrate de que este nombre coincida con tu archivo .cshtml
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - pc2_leonardo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/pc2_leonardo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">pc2_leonardo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <partial name="_MenuAdminPartial" />
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - pc2_leonardo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MenuAdminPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Collections.Generic;

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    IdentityUser myidentity  = await Task.Run(() => UserManager.GetUserAsync(User));
    var roles = await Task.Run(() => UserManager.GetRolesAsync(myidentity));

    @if(roles.Contains("admin") ){
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta_Bancaria" asp-action="ListarCuentas" >Listado</a>
        </li>
    }else{
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta_Bancaria" asp-action="Index" >Crear Cuenta</a>
        </li>
    }

}